title: Michael Rodriguez - Economic Analyst and Author
description: >-
  Official website of Michael Rodriguez, renowned economic analyst and author of 
  insightful books on global economics, financial markets, and technological disruption.
lang: en
theme: jekyll-theme-cayman
url: "https://zews123.github.io"
baseurl: "/michael-rodriguez-books"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
# SEO settings
twitter:
  username: MRodriguezBooks
  card: summary_large_image
social:
  name: Michael Rodriguez
  links:
    - https://x.com/Youvideo1
    - https://www.facebook.com/MichaelRodriguezAuthor/
# Отключаем добавление названия сайта к заголовкам страниц
title_separator: ""
# Настройки для sitemap
sitemap:
  filename: sitemap.xml
  exclude:
    - "/404.html"
    - "/assets/css/style.scss"
# Google Analytics (добавьте свой ID позже)
# google_analytics: UA-XXXXXXXXX-X
